### ISSUE TITLE
annotator.py error out 

### ISSUE THREAD

**Issue by ecwheele** [byee4/annotator#1]
Command:
[ecwheele@tscc-login1 ica_testing]$ python /home/bay001/projects/codebase/annotator/annotate.py --input /projects/ps-yeolab3/ecwheele/20170627_srsf2_all_rnaseq_eirini/outrigger/EW69_outrigger/outrigger_output/psi/outrigger_psi.bed --output /projects/ps-yeolab3/ecwheele/20170627_srsf2_all_rnaseq_eirini/outrigger/EW69_outrigger/outrigger_output/psi/outrigger_psi.annotated.bed --gtfdb /projects/ps-yeolab/genomes/hg19/gencode_v19/gencode.v19.annotation.gtf.db

Error:
Initializing/creating defs:  14%|###8                       | 1/7 [00:00<00:01,  3.33it/s]featuretypes = ['cds', 'selenocysteine', 'utr', 'exon', 'gene', 'start_codon', 'stop_codon', 'transcript']
Building gene ids -> gene names dictionary:  29%|###1       | 2/7 [00:15<00:23,  4.71s/it]Traceback (most recent call last):                                 | 0/25 [00:00<?, ?it/s]
  File "/home/bay001/projects/codebase/annotator/annotate.py", line 183, in <module>
    main()
  File "/home/bay001/projects/codebase/annotator/annotate.py", line 179, in main
    transcript_priority, gene_priority, species, append_chr, fuzzy
  File "/home/bay001/processing_scripts/codebase/annotator/Annotator.py", line 668, in annotate
    annotator = Annotator(db_file, chroms, species, append_chr, fuzzy)
  File "/home/bay001/processing_scripts/codebase/annotator/Annotator.py", line 71, in __init__
    self._hash_features(append_chr, fuzzy)
  File "/home/bay001/processing_scripts/codebase/annotator/Annotator.py", line 149, in _hash_features
    for element in self._db.region(seqid=chrom):
TypeError: region() got an unexpected keyword argument 'seqid'

**Comment by byee4** [comment]
Hm this seems like the region() doesn't like the seqid arg. Can you check to see if FeatureDB.region works properly?
 
<a link>https://pythonhosted.org/gffutils/autodocs/gffutils.FeatureDB.region.html#gffutils.FeatureDB.region</a>

**Comment by ecwheele** [comment]
gtfdb = "/projects/ps-yeolab/genomes/hg19/gencode_v19/gencode.v19.annotation.gtf.db"
db = gffutils.FeatureDB(gtfdb)
gffutils.FeatureDB.region(db, seqid = "chr1")

This returns a generator object with no errors.

<generator object region at 0x2b1ac7ba2730>

**Comment by byee4** [comment]
Running off of an interactive node or using more memory fixed this problem.
